CREATE SCHEMA IF NOT EXISTS SCHEMA1;
CREATE SCHEMA IF NOT EXISTS SCHEMA2;

SET SCHEMA SCHEMA1;
CREATE TABLE User (
  id         INTEGER PRIMARY KEY,
  name VARCHAR(30),
  email  VARCHAR(50)
);
CREATE TABLE Idempotent (
  key VARCHAR(30),
  value  BOOLEAN
);

SET SCHEMA SCHEMA2;
CREATE TABLE User (
  id         INTEGER PRIMARY KEY,
  name VARCHAR(30),
  email  VARCHAR(50)
);